### ISSUE TITLE
How to use selma with  gradle

### ISSUE THREAD

**Issue by winsnow** [xebia-france/selma#151]
I have add the libs into build.gradle:  
```
compile group: 'fr.xebia.extras', name: 'selma-processor', version: '0.15'
compile group: 'fr.xebia.extras', name: 'selma', version: '0.15'
```

But when do a getting start, it not work, just throw exception: 
```
Exception in thread "main" java.lang.IllegalArgumentException: Unable to load generated mapper class com.test.l4dto.selma.OrderSelmaMapperSelmaGeneratedClass failed : com.test.l4dto.selma.OrderSelmaMapperSelmaGeneratedClass
	at fr.xebia.extras.selma.Selma.createMapperInstance(Selma.java:255)
	at fr.xebia.extras.selma.Selma.getMapper(Selma.java:158)
	at fr.xebia.extras.selma.Selma.access$100(Selma.java:56)
	at fr.xebia.extras.selma.Selma$MapperBuilder.build(Selma.java:349)
	at com.test.l4dto.selma.DtoMapping.main(DtoMapping.java:15)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.ClassNotFoundException: com.test.l4dto.selma.OrderSelmaMapperSelmaGeneratedClass
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at fr.xebia.extras.selma.Selma.createMapperInstance(Selma.java:183)

```

I find the different is the maven project has a plugin, how to use the plugin with gradle?

**Comment by slemesle** [comment]
The compiler should handle SelmaProcessor by default. 
I am not a Gradle user, the error reveals that the processor was not taken into account by the compiler. But I can not say why !
You can either add the compiler flags ("-processor", "fr.xebia.extras.selma.codegen.MapperProcessor"), or add the gradle apt plugin [https://github.com/tbroyer/gradle-apt-plugin]. 

I hope you'll get the ride of it, and if you can provide some documentation we can include the site that would be awsome.

**Comment by slemesle** [comment]
Hi @winsnow,
if you closed this issue, I hope you get the ride of it. 
Can you share your solution for other users ?

Thanks

**Comment by hamavaro** [comment]
Hi ! 
I have had the same issue! Using [https://github.com/tbroyer/gradle-apt-plugin] like @slemesle suggested, fixes the issue. 

Thanks

**Comment by slemesle** [comment]
Hi @hamavaro,

thanks for your feedback, is it possible for you to share a gradle file sample to add it as documentation on the site or a sample project ?

**Comment by hamavaro** [comment]
Yeah of course, 
Here is the gradle file including, spring boot + Selma Mapper + Lombok + some other dependencies.

`
buildscript {
    ext {
        springBootVersion = '2.0.0.BUILD-SNAPSHOT'
        checkstyleVersion = '7.7'
        selmaMapperVersion = '1.0'
    }
    repositories {
        mavenCentral()
        maven { url "https://repo.spring.io/snapshot" }
        maven { url "https://repo.spring.io/milestone" }
        maven { url "https://plugins.gradle.org/m2/" }
    }
    dependencies {
        classpath("org.springframework.boot:spring-boot-gradle-plugin:${springBootVersion}")
        classpath(group: 'fr.xebia.extras', name: 'selma', version: selmaMapperVersion)
        classpath "net.ltgt.gradle:gradle-apt-plugin:0.10"
    }
}

apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'org.springframework.boot'
apply plugin: 'io.spring.dependency-management'
apply plugin: 'checkstyle'
apply plugin: "net.ltgt.apt"

version = '0.0.1-SNAPSHOT'
sourceCompatibility = 1.8


repositories {
    mavenCentral()
    maven { url "https://repo.spring.io/snapshot" }
    maven { url "https://repo.spring.io/milestone" }
}

dependencies {
    compile('org.springframework.boot:spring-boot-starter-data-jpa') {
        exclude module: "logback-classic"
    }
    compile('org.springframework.boot:spring-boot-starter-security') {
        exclude module: "logback-classic"
    }
    compile('org.springframework.boot:spring-boot-starter-web') {
        exclude module: "logback-classic"
    }
    compile('org.json:json:20160212')
    compile('org.projectlombok:lombok')
    compile('org.hibernate:hibernate-core:5.2.10.Final')
    compile(group: 'org.slf4j', name: 'slf4j-simple', version: '1.7.25')
    compile(group: 'org.json', name: 'json')
    compile(group: 'fr.xebia.extras', name: 'selma', version: selmaMapperVersion)
    compile(group: 'fr.xebia.extras', name: 'selma-processor', version: selmaMapperVersion)

    runtime('org.postgresql:postgresql')

    testCompile('org.springframework.boot:spring-boot-starter-test') {
        exclude module: "logback-classic"
    }
}

checkstyle {
    ignoreFailures = false
    configFile = new File("config/checkstyle/gradle-google-checkstyle.xml")
    toolVersion = checkstyleVersion
}

// Modify checkstyle to generate an exception on checkstyle warnings.
tasks.withType(Checkstyle).each { checkstyleTask ->
    checkstyleTask.doLast {
        reports.all { report ->
            def outputFile = report.destination
            if (outputFile.exists() && outputFile.text.contains("<error ")) {
                throw new GradleException("There were checkstyle warnings! For more info check $outputFile")
            }
        }
    }
}

`

**Comment by vratojr** [comment]
Hello, as a syntetic explanation, to use selma with gradle you can:
Add the apt plugin:

```
plugins {
    id "net.ltgt.apt" version "0.10"
}

```
and just import the selma packages:

```
    compile group: 'fr.xebia.extras', name: 'selma', version:'1.0'
    compile group: 'fr.xebia.extras', name: 'selma-processor', version:'1.0' //Have the processor used by the apt plugin
```

Plus extra config if you want to decide where to deploy your generated files:

```
sourceSets {
  main {
	//Target directory for annotation processor when processing
  	output.generatedSourcesDir = "$project.buildDir/generated/selma"
  }
}
```

**Comment by Rubenmp** [comment]
Just in case it helps someone. I made it work using this in **build.gradle** file:
```
dependencies {
	annotationProcessor 'fr.xebia.extras:selma-processor:1.0'
	implementation 'fr.xebia.extras:selma:1.0'
}
```
then you can declare the mapper using:
```
SelmaMapper mapper = Selma.builder(SelmaMapper.class).build();
```
where SelmaMapper is my custom mapper whose implementation will be generated at compilation time
```
@Mapper
public interface SelmaMapper {
    ProductDetail toProductDetailInterface(com.mca.yourapp.service.dto.ProductDetail input);
}
```

Check this [tutorial](https://tomgregory.com/annotation-processors-in-gradle-with-the-annotationprocessor-dependency-configuration/) (or [video](https://www.youtube.com/watch?v=EMdavUDRmy4&ab_channel=TomGregory)) for a better understanding of annotation processors.
