### ISSUE TITLE
How to use selma with maven

### ISSUE THREAD

**Issue by lionchi** [xebia-france/selma#205]
I have add the libs into pom.iml
<dependency>
            <groupId>fr.xebia.extras</groupId>
            <artifactId>selma-processor</artifactId>
            <version>1.0</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>fr.xebia.extras</groupId>
            <artifactId>selma</artifactId>
            <version>1.0</version>
        </dependency>
But when do a getting start, it not work, just throw exception:
Unable to load generated mapper class com.gavrilov.core.mappers.UserMapperSelmaGeneratedClass failed : com.gavrilov.core.mappers.UserMapperSelmaGeneratedClass]
java.lang.IllegalArgumentException: Unable to load generated mapper class com.gavrilov.core.mappers.UserMapperSelmaGeneratedClass failed : com.gavrilov.core.mappers.UserMapperSelmaGeneratedClass
	at fr.xebia.extras.selma.Selma.createMapperInstance(Selma.java:255)
	at fr.xebia.extras.selma.Selma.getMapper(Selma.java:158)
	at fr.xebia.extras.selma.Selma.access$100(Selma.java:56)
	at fr.xebia.extras.selma.Selma$MapperBuilder.build(Selma.java:349)

**Comment by NitinNanda** [comment]
I am facing the same issue
