### ISSUE TITLE
NullPointerException on IntelliJ compiling

### ISSUE THREAD

**Issue by antoinemichaud** [xebia-france/selma#59]
Hello,

I can't compile anymore my project. When I click on "make", I get a NullPointerException. When I look in the build.log of IntelliJ, I can see this stack :

`2015-07-03 10:44:10,386 [   2634]   INFO - s.incremental.java.JavaBuilder - java.lang.NullPointerException
java.lang.RuntimeException: java.lang.NullPointerException
	at com.sun.tools.javac.main.Main.compile(Main.java:469)
	at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:132)
	at org.jetbrains.jps.javac.JavacMain.compile(JavacMain.java:168)
	at org.jetbrains.jps.incremental.java.JavaBuilder.compileJava(JavaBuilder.java:382)
	at org.jetbrains.jps.incremental.java.JavaBuilder.compile(JavaBuilder.java:296)
	at org.jetbrains.jps.incremental.java.JavaBuilder.doBuild(JavaBuilder.java:204)
	at org.jetbrains.jps.incremental.java.JavaBuilder.build(JavaBuilder.java:176)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runModuleLevelBuilders(IncProjectBuilder.java:1196)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuildersForChunk(IncProjectBuilder.java:877)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildTargetsChunk(IncProjectBuilder.java:945)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunkIfAffected(IncProjectBuilder.java:840)
	at org.jetbrains.jps.incremental.IncProjectBuilder.buildChunks(IncProjectBuilder.java:663)
	at org.jetbrains.jps.incremental.IncProjectBuilder.runBuild(IncProjectBuilder.java:370)
	at org.jetbrains.jps.incremental.IncProjectBuilder.build(IncProjectBuilder.java:191)
	at org.jetbrains.jps.cmdline.BuildRunner.runBuild(BuildRunner.java:137)
	at org.jetbrains.jps.cmdline.BuildSession.runBuild(BuildSession.java:293)
	at org.jetbrains.jps.cmdline.BuildSession.run(BuildSession.java:124)
	at org.jetbrains.jps.cmdline.BuildMain$MyMessageHandler$1.run(BuildMain.java:242)
	at org.jetbrains.jps.service.impl.SharedThreadPoolImpl$1.run(SharedThreadPoolImpl.java:41)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at fr.xebia.extras.selma.codegen.MapperMethodGenerator.generateStack(MapperMethodGenerator.java:184)
	at fr.xebia.extras.selma.codegen.MapperMethodGenerator.buildMappingMethod(MapperMethodGenerator.java:98)
	at fr.xebia.extras.selma.codegen.MapperMethodGenerator.build(MapperMethodGenerator.java:59)
	at fr.xebia.extras.selma.codegen.MapperClassGenerator.build(MapperClassGenerator.java:123)
	at fr.xebia.extras.selma.codegen.MapperProcessor.generateMappingClassses(MapperProcessor.java:88)
	at fr.xebia.extras.selma.codegen.MapperProcessor.process(MapperProcessor.java:73)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:793)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:722)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1700(JavacProcessingEnvironment.java:97)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1029)
	at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1163)
	at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1108)
	at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:824)
	at com.sun.tools.javac.main.Main.compile(Main.java:439)
	... 23 more`

Notice that if I compile with maven, all looks well. This only happens on IntelliJ compilation. 

In IntelliJ, my compiler is Javac 1.7 and my annotation processors is enabled (by default).

Have you any idea of the origin of the problem ?

Thank you

**Comment by SergioArrighi** [comment]
I have same issue in a different scenario, for me this happens when I add a particular runtime maven dependency to a project which is using Selma. No idea of the cause.
Regards

**Comment by pSub** [comment]
I have the same issue as well. I also think it is caused by a particular maven dependency, because deleting my local repository fixes the issue. However I was never able to reproduce it.
